#' Defines Nucleotide Palette
nucleotide_pal <- c("A"= "#64F83F", 
                    "G"= "#EB413C",
                    "C"= "#FFB340", 
                    "T"= "#288BEA", 
                    "U"= "#288BEA")
purine_pyrimidine_pal <- c("A"= "FF86F6", 
                           "G"="36DFCF",
                           "C"= "FF86F6", 
                           "T"= "36DFCF", 
                           "U"= "36DFCF",
                           "R"= "FF86F6",
                           "Y"= "36DFCF")
#' Defines basic Palette
default_pal <- c("A" = "limegreen", "G" = "lightgreen",
               "C" = "hotpink1", "T" = "red",
               "U" = "lightsalmon", "J" = "maroon",
               "B" = "snow", "O" = "mediumorchid",
               "D" = "lemonchiffon", "E" = "lightseagreen",
               "N" = "darkgreen", "Q" = "thistle",
               "I" = "darkorange", "L" = "lightcyan",
               "M" = "dodgerblue", 
               "F" = "gray30", "W" = "black",
               "Y" = "plum", "V" = "yellow",
               "H" = "navy", "Z" = "tan",
               "K" = "rosybrown4", "R" = "lightgoldenrod",
               "P" = "salmon", "-" = null_color,
               "S" = "darkred", "X" = "black")
default_nuc_pal <- c("A" = "limegreen", "G" = "lightgreen",
                 "C" = "hotpink1", "T" = "red",
                 "U" = "red")
default_char_pal <- c("0" = "limegreen", "1" = "lightgreen",
                      "2" = "hotpink1", "3" = "red",
                      "4" = "red")
#' Defines Ocean Palette
ocean_pal <- c("A" = "turquoise", "G" = "lightgreen",
               "C" = "turquoise4", "T" = "tan4",
               "U" = "steelblue", "J" = "springgreen4",
               "B" = "seashell", "O" = "seashell4",
               "D" = "seagreen", "E" = "dodgerblue",
               "N" = "skyblue", "Q" = "skyblue4",
               "I" = "lightsalmon", "L" = "lightcyan",
               "M" = "black", 
               "F" = "blue", "W" = "hotpink",
               "Y" = "navajowhite", "V" = "white",
               "H" = "navy", "Z" = "tan",
               "K" = "plum", "R" = "lightgoldenrod",
               "P" = "orange", "-" = null_color,
               "S" = "gray45", "X" = "aquamarine2")
#' Defines Forest Palette
forest_pal <- c("A" = "forestgreen", "G" = "darkgreen",
                "C" = "saddlebrown", "T" = "tan4",
                "U" = "brown4", "J" = "springgreen4",
                "B" = "black", "O" = "goldenrod4",
                "D" = "seagreen", "E" = "peru",
                "N" = "darkseagreen", "Q" = "navy",
                "I" = "wheat4", "L" = "orange",
                "M" = "skyblue", 
                "F" = "olivedrab4", "W" = "firebrick4",
                "Y" = "white", "V" = "indianred",
                "H" = "khaki4", "Z" = "tan",
                "K" = "sienna1", "R" = "beige",
                "P" = "black", "-" = null_color,
                "S" = "moccasin", "X" = "peachpuff4")
#' Defines Fire Palette
fire_pal <- c("A" = "red", "G" = "orange",
              "C" = "yellow", "T" = "firebrick4",
              "U" = "brown", "J" = "tan",
              "B" = "saddlebrown", "O" = "goldenrod",
              "D" = "salmon", "E" = "chocolate",
              "N" = "gray45", "Q" = "paleturquoise",
              "I" = "burlywood4", "L" = "mistyrose3",
              "M" = "wheat", "V" = "sienna4",
              "F" = "sandybrown", "W" = "sienna",
              "Y" = "lavender", "V" = "indianred",
              "H" = "khaki", "Z" = "moccasin",
              "K" = "black", "R" = "white",
              "P" = "lightgoldenrod", "-" = null_color,
              "S" = "tomato", "X" = "black")
#' Defines Floral Palette
floral_pal <- c("A" = "chartreuse2", "G" = "orange",
                "C" = "yellow", "T" = "red",
                "U" = "pink", "J" = "dodgerblue",
                "B" = "plum", "O" = "thistle",
                "D" = "salmon", "E" = "darkblue",
                "N" = "violet", "Q" = "paleturquoise",
                "I" = "steelblue", "L" = "peru",
                "M" = "purple", "V" = "purple4",
                "F" = "palevioletred", "W" = "black",
                "Y" = "palegreen", "V" = "white",
                "H" = "lavender", "Z" = "honeydew2",
                "K" = "darkorange3", "R" = "aquamarine",
                "P" = "mistyrose3", "-" = null_color,
                "S" = "wheat", "X" = "black")
# Defines clustal palette
clustal_pal <- c("A" = "#80A0F0", "G" = "#F09048",
                 "C" = "#F08080", "T" = "#00FF00",
                 "U" = "cornsilk", "J" = "cornsilk",
                 "B" = "black", "O" = "cornsilk",
                 "D" = "#C048C0", "E" = "#C048C0",
                 "N" = "#00FA00", "Q" = "#00FF00",
                 "I" = "#80A08C", "L" = "#80A0F0",
                 "M" = "#80A0F0", 
                 "F" = "#80A0F0", "W" = "#80A0F0",
                 "Y" = "#15A4A4", "V" = "#80A0F0",
                 "H" = "#15A4A4", "Z" = "black",
                 "K" = "#F01505", "R" = "#F01505",
                 "P" = "#FFFF00", "-" = null_color,
                 "S" = "#00FF00", "X" = "black")
nuc_clustal_pal <- c("A" = "#88B5E4", 
                     "G" = "#DB9B58", 
                     "C" = "#D88885", 
                     "T" = "#67C219", 
                     "U" = "#67C219")
# Defines Zappo Palette
zappo_pal <- c("A" = "#FFAFAF", "G" = "#FF00FF",
               "C" = "#FFFF00", "T" = "#00FF00",
               "U" = "cornsilk", "J" = "cornsilk",
               "B" = "black", "O" = "cornsilk",
               "D" = "#FF0000", "E" = "#FF0000",
               "N" = "#00FF00", "Q" = "#00FF00",
               "I" = "#FFAFAF", "L" = "#FFAFAF",
               "M" = "#FFAFAF", 
               "F" = "#FFC800", "W" = "#FFC800",
               "Y" = "#FFC800", "V" = "#FFAFAF",
               "H" = "#6464FF", "Z" = "black",
               "K" = "#6464FF", "R" = "#6464FF",
               "P" = "#FF00FF", "-" = null_color,
               "S" = "#00FF00", "X" = "black")
# Defines Taylor Palette
taylor_pal <- c("A" = "#CCFF00", "G" = "#FF9900",
                "C" = "#FFFF00", "T" = "#FF6600",
                "U" = "cornsilk", "J" = "cornsilk",
                "B" = "black", "O" = "cornsilk",
                "D" = "#FF0000", "E" = "#FF0066",
                "N" = "#CC00FF", "Q" = "#FF00CC",
                "I" = "#66FF00", "L" = "#33FF00",
                "M" = "#00FF00", 
                "F" = "#00FF66", "W" = "#00CCFF",
                "Y" = "#00CCFF", "V" = "#99FF00",
                "H" = "#0066FF", "Z" = "black",
                "K" = "#6600FF", "R" = "#0000FF",
                "P" = "#FFCC00", "-" = null_color,
                "S" = "#FF3300", "X" = "black")
# Defines Hydrophobicity palette
hydrophobicity_pal <- c("A" = "#AD0052", "G" = "#6A0095",
                 "C" = "#C2003D", "T" = "#61009E",
                 "U" = "cornsilk", "J" = "cornsilk",
                 "B" = "#0C00F3", "O" = "cornsilk",
                 "D" = "#0C00F3", "E" = "#0C00F3",
                 "N" = "#0C00F3", "Q" = "#0C00F3",
                 "I" = "#FF0000", "L" = "#EA0015",
                 "M" = "#B0004F", 
                 "F" = "#CB0034", "W" = "#5B00A4",
                 "Y" = "#4F00B0", "V" = "#F60009",
                 "H" = "#1500EA", "Z" = "#0C00F3",
                 "K" = "#0000FF", "R" = "#0000FF",
                 "P" = "#4600B9", "-" = null_color,
                 "S" = "#5E00A1", "X" = "#680097")
# Defines Helix Propensity Palette
helix_propensity_pal <- c("A" = "#E718E7", "G" = "#00FF00",
                          "C" = "#23DC23", "T" = "#47B847",
                          "U" = "cornsilk", "J" = "cornsilk",
                          "B" = "#49B649", "O" = "cornsilk",
                          "D" = "#778877", "E" = "#FF00FF",
                          "N" = "#1BE41B", "Q" = "#926D92",
                          "I" = "#8A758A", "L" = "#AE51AE",
                          "M" = "#EF10EF", 
                          "F" = "#986798", "W" = "#8A758A",
                          "Y" = "#21DE21", "V" = "#857A85",
                          "H" = "#758A75", "Z" = "#C936C9",
                          "K" = "#A05FA0", "R" = "#6F726F",
                          "P" = "#00FF00", "-" = null_color,
                          "S" = "#36C936", "X" = "#758A75")
# Defines Strand Propensity Palette
strand_propensity_pal <- c("A" = "#5858A7", "G" = "#4949B6",
                           "C" = "#9D9D62", "T" = "#9D9D62",
                           "U" = "cornsilk", "J" = "cornsilk",
                           "B" = "#4343BC", "O" = "cornsilk",
                           "D" = "#2121DE", "E" = "#0000FF",
                           "N" = "#64649B", "Q" = "#8C8C73",
                           "I" = "#ECEC13", "L" = "#B2B24D",
                           "M" = "#82827D", 
                           "F" = "#C2C23D", "W" = "#C0C03F",
                           "Y" = "#D3D32C", "V" = "#FFFF00",
                           "H" = "#60609F", "Z" = "#4747B8",
                           "K" = "#4747B8", "R" = "#6B6B94",
                           "P" = "#2323DC", "-" = null_color,
                           "S" = "4949B6", "X" = "#797986")
turn_propensity_pal <- c("A" = "#2CD3D3", "G" = "#FF0000",
                           "C" = "#A85757", "T" = "#738C8C",
                           "U" = "cornsilk", "J" = "cornsilk",
                           "B" = "#F30C0C", "O" = "cornsilk",
                           "D" = "#E81717", "E" = "#778888",
                           "N" = "#FF0000", "Q" = "#3FC0C0",
                           "I" = "#00FFFF", "L" = "#1CE3E3",
                           "M" = "#1EE1E1", 
                           "F" = "#1EE1E1", "W" = "#738C8C",
                           "Y" = "#9D6262", "V" = "#07F8F8",
                           "H" = "#708F8F", "Z" = "#5BA4A4",
                           "K" = "#7E8181", "R" = "#708F8F",
                           "P" = "#F60909", "-" = null_color,
                           "S" = "#E11E1E", "X" = "#7C8383")
# Defines Buried Index Palette
buried_index_pal <- c("A" = "#00A35C", "G" = "#009D62",
                      "C" = "#0000FF", "T" = "#00DB24",
                      "U" = "cornsilk", "J" = "cornsilk",
                      "B" = "#00EB14", "O" = "cornsilk",
                      "D" = "#00EB14", "E" = "#00F10E",
                      "N" = "#00EB14", "Q" = "#00F10E",
                      "I" = "#0054AB", "L" = "#007B84",
                      "M" = "#009768", 
                      "F" = "#008778", "W" = "#00A857",
                      "Y" = "#00E619", "V" = "#00FD14",
                      "H" = "#00D52A", "Z" = "#00F10E",
                      "K" = "#00FF00", "R" = "#00FC03",
                      "P" = "#00E01F", "-" = null_color,
                      "S" = "#00D52A", "X" = "#00B649")





